### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-honduras#10]
# Description

For the duration of the work, yet after the stakeholders have approved the staging site, we will host the production site.

# Tasks

- [ ] Do all steps to set up a production site with our DevOps team
- [ ] Deploy production site
- [ ] Code and setup meetings our [coding standards](https://github.com/okfn/coding-standards)
