### ISSUE TITLE
Define the process for operational support

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-honduras#13]
# Description

We need a simple and clear protocol for operational support.

# Tasks

- [ ] Define the process
- [ ] Sign-off from product owner
- [ ] Sign-off from client

**Comment by michellecbox** [comment]
N/A
