### ISSUE TITLE
Training discovery document

### ISSUE THREAD

**Issue by jobarratt** [datopian/ckanext-honduras#14]
# Description

Create a discovery document: A form designed to capture the information we need to plan the in person training and prepare a full plan and list of training materials to produce. 

https://docs.google.com/document/d/1U0TKKwyrmSvOBzzZjkYeBGJpcQDdcL6P__M_gvnsge4/edit

# Tasks

- [x] review and update existing form template
- [x] Oscar to review and add questions relating to in person training
- [x] Jo to review based on additional needs
- [x] Review by Product Owner
- [x] Michelle to review and send
- [ ] Form completed and returned

**Comment by michellecbox** [comment]
done by @jobarratt
