### ISSUE TITLE
Plan for in-person training

### ISSUE THREAD

**Issue by jobarratt** [datopian/ckanext-honduras#15]
# Description

To create a top level planning sessions schedule for the 2 day in person training session in Honduras 

https://docs.google.com/document/d/1Ca4hz3BjkIjr_kmba5yE_wxnHvr2t-LVOs2smD9oR2g/edit

# Tasks

- [x] review existing documentation and materials
- [x] Create plan 
- [ ] review by PM
- [ ] Share with client for comment
- [ ] create list of content creation 'tasks'

**Comment by jobarratt** [comment]
closed in favour of https://github.com/datopian/ckanext-honduras/issues/25
