### ISSUE TITLE
Familiarization with CKAN Design development / coding standards

### ISSUE THREAD

**Issue by tanvirchahal** [datopian/ckanext-honduras#17]
# Description

As a designer who hasn't worked with ckan i need to get familiar with design development in a running ckan instance.

# Tasks

- [x] Go through ckan frontend development guidelines https://docs.ckan.org/en/2.8/contributing/frontend/index.html
- [x] Setup ckan on local for practice
- [x] Try Quick updates on nav, home and dataset page to get an idea of how customizations work on running ckan
- [x] Submit estimate for HTML / CSS task #6

**Comment by tanvirchahal** [comment]
* Have gone through the concepts of templating in ckan
* created new extensitions and extended templates
* made updates to homepage, dataset, navigations and other visual elements
