### ISSUE TITLE
Implement approved design in HTML/CSS (Datasets, About)

### ISSUE THREAD

**Issue by tanvirchahal** [datopian/ckanext-honduras#18]
# Description

After #6 we need to implement the designs for the dataset and about pages.

# Tasks

- [x] Restructure the datasets template according to mockups
- [x] Implement design updates for about page
- [x] Implement the mocked designs  for datasets as HTML/CSS
- [x] Get sign-off from internal product owner
- [x] Code and setup meetings our [coding standards](https://github.com/okfn/coding-standards)

## Pages to cover

- [x] Datasets
- [x] About
