### ISSUE TITLE
Share Hosting options and questionnaire

### ISSUE THREAD

**Issue by michellecbox** [datopian/ckanext-honduras#19]
# Description

WB has requested a questionnaire to address what it takes for GoH to self host the portal.

# Tasks

- [x] Create questionnaire 
- [x] Share with WB for feedback 
- [x] Share with GoH 
- [ ] GoH to fill in questionnaire 
- [ ] Setup a session to discuss Hosting options (Datopian and GoH)
- [ ] GoH to make a decision on Hosting preference

**Comment by pwalsh** [comment]
@michellecbox didn't we do this?

**Comment by michellecbox** [comment]
@pwalsh we did (delivered questionnaire in Spanish, explained process and skills expected etc and delivered quote to WB) but not all tasks are completed, Marcela from WB is still talking to GoH about this and they should make a decision by early next week.
