### ISSUE TITLE
Setup CKAN extension for design and setup templating

### ISSUE THREAD

**Issue by tanvirchahal** [datopian/ckanext-honduras#20]
# Description

Setup ckan honduras extension on local and get the base css templating ready, like buttons , input forms, navbars and other ui elements designed. 

# Tasks

- [x] Get CKAN running locally
- [x] Set up a theme in the `ckanext-honduras` extension
- [x] Setup fonts 
- [x] Setup base css designs for navbar, buttons and other ui elements

**Comment by tanvirchahal** [comment]
consumed 4d
