### ISSUE TITLE
Implement HTML/CSS (Organizations, Groups)

### ISSUE THREAD

**Issue by tanvirchahal** [datopian/ckanext-honduras#21]
# Description

Implement design for categories and groups so they can be integrated with the CKAN data portal.

# Tasks

- [x] Start restructuring/designing organization page based on mockups
- [x] Start restructuring/designing groups page based on mockups
- [x] Implement Categories design as HTML/CSS
- [x] Implement Groups design as HTML/CSS
- [x] Get sign-off from internal product owner
- [x] Code and setup meetings our [coding standards](https://github.com/okfn/coding-standards)
