### ISSUE TITLE
Mobile Responsiveness and Optimizations

### ISSUE THREAD

**Issue by tanvirchahal** [datopian/ckanext-honduras#23]
# Description
Ensure that the Honduras portal scales on all mobile devices perfectly.

# Tasks

- [x] Setup datasets, organizations, groups on Honduras staging https://honduras-staging.ckan.io/organization
- [x] Perform responsive testing on various screens and devices
- [x] Make optimizations / updates
- [ ] Review by Paul
- [ ] Signoff by Paul

**Comment by tanvirchahal** [comment]
It's found that the top nav on staging is not getting styled properly and looks different from the version on local.  Currently inspecting the bug. 
![image](https://user-images.githubusercontent.com/13431329/57126293-1c68aa00-6daa-11e9-958d-6a3cd49ce3cc.png)

**Comment by tanvirchahal** [comment]
Nav icons are missing (on mobile)
![image](https://user-images.githubusercontent.com/13431329/57126369-5fc31880-6daa-11e9-9622-6fadaf548064.png)

**Comment by tanvirchahal** [comment]
Groups on mobile need fix
![image](https://user-images.githubusercontent.com/13431329/57126397-78cbc980-6daa-11e9-9ec1-90e086c4e953.png)

**Comment by tanvirchahal** [comment]
Search overlaps filters popup
![image](https://user-images.githubusercontent.com/13431329/57126429-91d47a80-6daa-11e9-9892-4fef7301db49.png)
