### ISSUE TITLE
Implement Design updates on Admin Pages 

### ISSUE THREAD

**Issue by tanvirchahal** [datopian/ckanext-honduras#24]
# Description

Ensure that the design elements of internal admin pages are consistently styled with rest of the Honduras theme.

# Tasks

- [x] Settings 
- [x] Acitivity Stream page
- [x] Manage Account Page
- [x] Dashboard page 
- [x] Subdashboard pages (news feed, my datasets, my organizations, my groups)
- [x] Sys admin pages

**Comment by pwalsh** [comment]
@michellecbox @tanvirchahal is this still pending?

**Comment by michellecbox** [comment]
@pwalsh still pending, Tanvir will have it ready by Tuesday next week

**Comment by michellecbox** [comment]
done
