### ISSUE TITLE
Government of Honduras training preparation

### ISSUE THREAD

**Issue by tlacoyodefrijol** [datopian/ckanext-honduras#25]
# Description

As part of the  development of the CKAN platform, OKFN will do a 2-day training with the Government of Honduras. 

# Tasks

- [ ] Mapping of resources
- [x] Development of a training plan
- [x] Approval by WB
- [ ] Approval by GoH
- [x] Development of training materials
