### ISSUE TITLE
Implement changes to Staging instance

### ISSUE THREAD

**Issue by michellecbox** [datopian/ckanext-honduras#27]
In order to make the staging environment more usable for GoH, WB has requested a list of changes to be implemented on the stating environment.

# Tasks

- [x] Enable Showcase extension  
- [x] Add Pages extension so that users can create custom pages
- [x] @borism Install and configure the harvesting extension on the site, with the RDF DCAT harvester so we can import [data.json](https://project-open-data.cio.gov/v1.1/schema/) files.
  -  [x] base harvest extension already installed, so you need to install and configure [ckanext-dcat](https://github.com/ckan/ckanext-dcat) and enable the `dcat_rdf_harvester` plugin.
- [x] @borism Add "CCBY 4.0" as the default option for the license schema
  - [x] Point to custom licenses file from the config on the cloud repository 
  - CC-BY-4.0 is one of the existing licence options (CKAN has a [cache of this file which is in use](https://licenses.opendefinition.org/licenses/groups/ckan.json)). Looks like we should override something [here](https://github.com/ckan/ckan/blob/master/ckan/templates/package/snippets/package_basic_fields.html#L34), but may be that there is a better place to do that.
- [x] @borism We need to provide a custom schema for datasets, and for data resources. For this, we leverage [ckanext-scheming](https://github.com/ckan/ckanext-scheming), which allows us to completely customise the stored and displayed metadata (displayed on dataset and data resource pages). The change itself is ultimately simple but requires a dive into details in CKAN. The [datasets tab in this spreadsheet](https://docs.google.com/spreadsheets/d/1D2UyTfHANXO5jO_RkBj5d6de5prkrpSe3KgYolBwTyk/edit#gid=1697736576) has the info:
  - Columns C-R are dataset custom fields
  - Columns S - AA are data resource custom fields
  - It is in Spanish :), but @amercader can help us with translations
  - Review this and then you and I will chat on the implementation
- [x] WB to provide a spreadsheet with metadata to be imported
  - [x] Create a one time script to import metadata from the provided spreadsheet 
- [x] Change language dropdown list to display "Spanish" as the default language for the portal
- [x] Share new features with WB for approval
- [ ] Share Staging site with GoH

**Comment by michellecbox** [comment]
WB asked if the Showcase extension that we will enable back can cover the ability to create new sites, so that we don't have to add the Pages extension?

**Comment by michellecbox** [comment]
fyi tasks marked as done were done locally but still need to be deployed and tested on staging.

@pwalsh showcase/pages extensions are done correct? I'm asking since Boris didn't work on them so just want to double check they are ready.

**Comment by michellecbox** [comment]
@borism 

Data that needs to be imported using a one-time script (ICF and SEFIN):
ICF: https://docs.google.com/spreadsheets/d/12q1oKtlinUtdESY9ItyQ168otIBOmiPvlJtV40tGYOk/edit?usp=sharing
SEFIN:  https://docs.google.com/spreadsheets/d/1xXVSsKSH_bG96zjVdiJHXp7crRZAsCRotLWuMq7jOZ4/edit?usp=sharing

Data that will be harvested through a data.json. I am pasting the link here just for reference
ONCAE: https://docs.google.com/spreadsheets/d/1gMoyiMDz34zDlct5l9sUnpLEzPJOuIz_tQre1nYg_Dg/edit?usp=sharing

**Comment by amercader** [comment]
@michellecbox @borism Full spec for the initial script here: https://github.com/datopian/ckanext-honduras/issues/38
