### ISSUE TITLE
Update staging instance logos/description

### ISSUE THREAD

**Issue by michellecbox** [datopian/ckanext-honduras#29]
Update staging instance logos/description to match GoH look and feel guidelines

# Tasks

- [x] WB to provide logos/description to be updated
- [x] Remove the "Userful Links" label
- [x]  Remove Privacy Policy link
- [x] Replace 
-- [ ]  About to Datos Abiertos de Honduras
-- [ ] Contact Us to Contacto
-- [ ] Open Government to Gobierno Abierto de Honduras
-- [ ]  About CNRA to Publica Datos
-- [ ] CKAN API to Desarrolladores
-- [ ] CKAN Association to Guía de Datos Abiertos
refer to spec [document](https://docs.google.com/document/d/1PSkq0LcsEzZtSFYY_9K6_3WjFw11-bRRdZa6sm6iAyQ/edit) 
- [x] Add the following text: "Este portal ha sido desarrollado con la asistencia técnica del Banco Mundial y con el financiamiento de la Agencia de los Estados Unidos para el Desarrollo Internacional (USAID)" at the bottom right side of the footer
- [x] Add USAID [logo](https://user-images.githubusercontent.com/13909143/60000843-4f6e4200-9665-11e9-973a-50532fca43be.png) on the top left of the previous text
- [x] Add WB logo (we have 2 options to choose from [1](https://github.com/datopian/ckanext-honduras/files/3319757/WB-Spanish-horizontal.zip) and [2](https://github.com/datopian/ckanext-honduras/files/3319758/WB-Spanish-vertical.zip)) on the top right of the previous text
- [x] Put Open data and CKAN logos next to each other (same line)
- [x] Share with WB
- [ ] Share with GoH

**Comment by michellecbox** [comment]
Resources:

[WB-Spanish-horizontal.zip](https://github.com/datopian/ckanext-honduras/files/3319757/WB-Spanish-horizontal.zip)

[WB-Spanish-vertical.zip](https://github.com/datopian/ckanext-honduras/files/3319758/WB-Spanish-vertical.zip)

![logo_usaid](https://user-images.githubusercontent.com/13909143/60000843-4f6e4200-9665-11e9-973a-50532fca43be.png)

Text: “Este portal ha sido desarrollado con la asistencia técnica del Banco Mundial y con el financiamiento de la Agencia de los Estados Unidos para el Desarrollo Internacional (USAID).”

**Comment by michellecbox** [comment]
@tanvirchahal  I am confirming with WB how these logos/text should be displayed before starting to work on this

**Comment by michellecbox** [comment]
Spec doc [here](https://docs.google.com/document/d/1PSkq0LcsEzZtSFYY_9K6_3WjFw11-bRRdZa6sm6iAyQ/edit)

**Comment by michellecbox** [comment]
done
