### ISSUE TITLE
Write inception report

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-honduras#3]
# Description

We will carry out a detailed assessment of the requirements Honduras’ Open Data Initiative based on information gathering exercises and interviews with key members of the team. Following analysis prepare a full report with recommendations which will inform subsequent work packages. 

# Tasks

- [x] Write inception report
  - [x] Input from collected materials
  - [x] Input from interviews
  - [x] Input from open data portal experience
  - [x] Section on hosting and infrastructure considerationsa
- [x] Share with stakeholders
- [x] Get sign-off

**Comment by pwalsh** [comment]
@michellecbox [v1 of report](https://docs.google.com/document/d/1GuL2qXW8JzGY8rB-01EdEek_8fIvqgyweBSw10mZaZM/edit#heading=h.x0vp4fw6ebmj).

It needs some basic input from @jobarratt and then I will do a quick edit, and we can send off for review, hopefully on Monday/Tuesday.

**Comment by michellecbox** [comment]
Closing as WB has approved. 
As an additional output, WB has requested a questionnaire to address what it takes for GoH to self host the portal. Issue #19
