### ISSUE TITLE
Create and link Static pages

### ISSUE THREAD

**Issue by michellecbox** [datopian/ckanext-honduras#30]
# Description
Once the "Pages" extension is enabled in https://honduras-staging.ckan.io/ the following static pages need to be created and linked to the corresponding footer links (Noticias is the only one that doesn't have a footer link)

- Datos Abiertos de Honduras
- Contacto
- Gobierno Abierto de Honduras
- Publica Datos
- Desarrolladores
- Guía de Datos Abiertos

# Tasks

- [ ] Create the following static pages with a generic text inside (client will update the text using the Pages extension)

- - [x] Datos Abiertos de Honduras
- - [x] Contacto
- - [x] Gobierno Abierto de Honduras
- - [x]  Publica Datos
- - [x] Desarrolladores
- - [x] Guía de Datos Abiertos
- [ ] Share with WB
- [ ] Share with GoH

**Comment by michellecbox** [comment]
done
