### ISSUE TITLE
Initial script for importing datasets

### ISSUE THREAD

**Issue by amercader** [datopian/ckanext-honduras#38]
## Description

Apart from the datasets that will be imported via harvesting there will be an initial load of datasets that have been compiled in two spreadsheets:
* [ICF](https://docs.google.com/spreadsheets/d/12q1oKtlinUtdESY9ItyQ168otIBOmiPvlJtV40tGYOk/edit?usp=sharing)
* [SEFIN](https://docs.google.com/spreadsheets/d/1xXVSsKSH_bG96zjVdiJHXp7crRZAsCRotLWuMq7jOZ4/edit?usp=sharing)

CSV versions: [Inventario Datasets ICF - SEFIN.zip](https://github.com/datopian/ckanext-honduras/files/3362088/Inventario.Datasets.ICF.-.SEFIN.zip)

Cleaned up CSV versions: 
[ICF_SEFIN_datasets_clean.zip](https://github.com/datopian/ckanext-honduras/files/3362253/ICF_SEFIN_datasets_clean.zip)

These CSVs can be further cleaned up if it helps with the script, but the modified versions should be included in the source code.

The spreadsheets contain metadata that matches the custom schema defined in #36.

Additionally, for the ICF data source, we need to upload some of the actual data files, currently hosted in a [Google Drive folder](https://drive.google.com/drive/folders/1MW1KgYcUUsD6t07rId-pX185_T-gja4x) and also shared on Slack.

We will work from the downloaded CSV versions of the spreadsheets. The python script will iterate over the rows, pulling the metadata fields for each dataset and its resources (distributions), building a JSON dict compatible with our schema and creating / updating the dataset via the API. Additionally, if there is a file linked to the dataset it will upload it (this cannot be done in the same step as creating the dataset)

# Tasks

- [x] Bootstrap a python command line script. It should take the CSV, CKAN URL and CKAN API key as parameters
- [x] Initial script that reads the CSV and correctly extracts all datasets with all its resources
- [x] Construct a valid CKAN dataset dict with the values of each row (row 4 contains the field name)
- [x] Use the API to check if a dataset exists, create if not or update if it does.
- [x] Add logic to upload ICF files. This can be part of the main import or a second command, whatever works. To link resource metadata on the spreadsheet to the actual files we can use resource identifier + format = file name (although it will require some tweaking like in ZIP files)
- [x] Once tested locally, run the script on the staging site

**Comment by amercader** [comment]
I've created a bootstrap script in 8cd02c6 (branch feature-38/import-script) to get you started @borism
