### ISSUE TITLE
Style guidelines for the portal

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-honduras#4]
# Description

If there are existing style guidelines for the portal, or for Government of Honduras web properties in general, we need them.

If there are not, we need to create a really basic style guide (primary color, secondary color, use of logo, font).

# Tasks

- [x] Analyze current honduras websites / documents, find if exisiting style guide
- [x] Prepare Invision Moodboard for Fonts / Color Palletes / Designs etc for inspiration
- [x] Create 2 versions of style guide
- [x] Updates based on feedback on style guide
- [x] Finalize styleguide

**Comment by michellecbox** [comment]
@tanvirchahal I just fwd you an email "Datos/contrataciones abiertas - introduccion equipo de gobierno digital" it contains:

1. Manual de Identidad Gráfica del Gobierno de la República de Honduras: This is an updated version of the document I showed you that has logos/color schemes/fonts
2. Manual de Desarrollo Web Version 2015: This is a manual for developing government websites, is only text and in spanish
3. A link to a government portal we can use as reference

We need to propose a basic style guide based on this

cc: @pwalsh

**Comment by pwalsh** [comment]
@tanvirchahal great. go ahead.

**Comment by tanvirchahal** [comment]
Updated Estimate: 3days

**Comment by tanvirchahal** [comment]
@michellecbox can you please review
Version 1: https://datopian.github.io/honduras-styleguide/index.html
Version 2: https://datopian.github.io/honduras-styleguide/version-2.html
