### ISSUE TITLE
UI mock designs

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-honduras#5]
# Description

Produce mock designs for 3 major pages on a CKAN data portal, with a maximum of an additional variation per page.

# Tasks

- [x] Mock designs
  - [x] Home page
  - [x] Dataset page
  - [x] Topic/category page
- [x] Get internal sign-off on the approach from the Product Owner
- [x] Share versions with client
- [x] Iteration/enhancement on approved version

**Comment by tanvirchahal** [comment]
Mockups https://xd.adobe.com/view/5ef4e7cc-4e0f-4200-60e2-26049f682a72-28c5/
