### ISSUE TITLE
Implement approved design in HTML/CSS (Home)

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-honduras#6]
# Description

After https://github.com/ViderumGlobal/ckanext-honduras/issues/5 we need to implement the designs so they can be integrated with the CKAN data portal.

# Tasks

- [x] Implement the homepage mocked designs as HTML/CSS
- [x] Implement remaining style elements so that the whole portal is consistently styled
- [x] implement new groups and organizations design on homepage
- [x] Get sign-off from internal product owner
- [x] Code and setup meetings our [coding standards](https://github.com/okfn/coding-standards)

## Pages to cover

- [x] Home

**Comment by tanvirchahal** [comment]
@michellecbox we would require the assets for logos for the project.  Can you please check with the client regarding logo assets.

**Comment by tanvirchahal** [comment]
On homepage, ckan is only showing 1 featured group and 1 featured organization.

As per the mockup, we need 3 featured groups and organizations. Not sure how to increase the limit for the featured groups.

**Comment by tanvirchahal** [comment]
consumed 4d
