### ISSUE TITLE
Deploy vanilla CKAN to staging environment

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-honduras#7]
# Description

In order to deploy a complete staging instance of the data portal, we want to start by spiking a vanilla CKAN deploy into our staging environment.

# Tasks

- [x] Get vanilla CKAN running locally
- [x] Ask DevOps team for setup of a staging environment 
- [x] Take steps to deploy to staging environment
- [x] Review deploy with product owner
- [x] Code and setup meetings our [coding standards](https://github.com/okfn/coding-standards)

**Comment by pwalsh** [comment]
Merged into https://github.com/datopian/ckanext-honduras/issues/8
