### ISSUE TITLE
Deploy staging environment

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckanext-honduras#8]
# Description

Deploy a complete staging instance of the data portal.

## Required extensions

- [x] this repo
- [x] harvest
- [x] datastore
- [x] geoview
- [x] pdfview
- [x] googleanalytics
- [x] spatial
- [x] showcase

## Required credentials

- [x] admin user for @tanvirchahal 
- [x] admin user for @pwalsh 
- [x] admin user for @michellecbox 

# Tasks

- [x] Deploy to staging ( honduras-staging.ckan.io )
- [x] Add some dummy test data with this command: https://docs.ckan.org/en/2.8/maintaining/getting-started.html?highlight=create-test-data#creating-test-data
- [x] Ley us know it is deployed

**Comment by pwalsh** [comment]
thx.
